version: '3'

services:
  simplelist:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: simplelist_chall
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9003:9003"
    entrypoint: /etc/init.sh
