version: "3"

services:
  app:
    build: ./app
    environment:
      - JWT_SECRET_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  secret:
    build: ./secret
    environment:
      - FLAG=fake{this_is_fake_flag}
  nginx:
    build: ./nginx
    ports:
      - 80:80
